"use client";

import { useState, useEffect, useRef } from "react";
import { useQuery } from "@tanstack/react-query";
import { FinancialSnapshot, ArchiveGrowthMetrics } from "@/core/types";
import { formatIndianNumber } from "@/core/services/currencyService";
import {
  TrendingUp,
  TrendingDown,
  Calendar,
  Wallet,
  ArrowUpRight,
  ArrowDownRight,
  Home,
  CreditCard,
  CheckCircle2,
  XCircle,
  RefreshCw,
} from "lucide-react";
import { Loader } from "@/shared/components/Loader";

const MONTHS = [
  "Jan",
  "Feb",
  "Mar",
  "Apr",
  "May",
  "Jun",
  "Jul",
  "Aug",
  "Sep",
  "Oct",
  "Nov",
  "Dec",
];

const FULL_MONTHS = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
];

export function ArchiveModule() {
  const currentYear = new Date().getFullYear();
  const currentMonth = new Date().getMonth() + 1;
  const [selectedYear, setSelectedYear] = useState<number>(currentYear);
  const [generatingMonths, setGeneratingMonths] = useState<Set<number>>(new Set());
  const [updatingMonths, setUpdatingMonths] = useState<Set<number>>(new Set());
  const hasAutoGenerated = useRef<Set<string>>(new Set());

  // Fetch available years
  const { data: yearsData } = useQuery<{ years: number[] }>({
    queryKey: ["archive-years"],
    queryFn: async () => {
      const response = await fetch("/api/archive?action=years");
      if (!response.ok) throw new Error("Failed to fetch years");
      return response.json();
    },
  });

  // Fetch all snapshots for the selected year
  const { data: yearSnapshots, isLoading, refetch: refetchSnapshots } = useQuery<{
    snapshots: FinancialSnapshot[];
  }>({
    queryKey: ["archive-year-snapshots", selectedYear],
    queryFn: async () => {
      const response = await fetch(`/api/archive?year=${selectedYear}`);
      if (!response.ok) {
        if (response.status === 404) {
          return { snapshots: [] };
        }
        throw new Error("Failed to fetch year snapshots");
      }
      return response.json();
    },
    enabled: !!selectedYear,
  });

  // Fetch 2025 December snapshot for comparison when viewing 2026
  const { data: year2025Snapshot } = useQuery<{
    snapshot?: FinancialSnapshot;
  }>({
    queryKey: ["archive-2025-snapshot"],
    queryFn: async () => {
      const response = await fetch(`/api/archive?year=2025&month=12`);
      if (!response.ok) {
        return { snapshot: undefined };
      }
      const data = await response.json();
      return { snapshot: data.snapshot };
    },
    enabled: selectedYear === currentYear,
  });

  // Auto-generate missing snapshots
  useEffect(() => {
    if (!isLoading && yearSnapshots && (selectedYear === currentYear || selectedYear === 2025)) {
      const snapshots = yearSnapshots.snapshots || [];
      const snapshotMap = new Map<number, FinancialSnapshot>();
      snapshots.forEach((snapshot) => {
        if (snapshot.month !== undefined) {
          snapshotMap.set(snapshot.month, snapshot);
        }
      });

      // Check for missing months and auto-generate
      // For 2025: only December
      // For current year: only past months (up to current month)
      const monthsToCheck = selectedYear === 2025 
        ? [12] 
        : Array.from({ length: currentMonth }, (_, i) => i + 1);
      
      const missingMonths = monthsToCheck.filter(month => !snapshotMap.has(month));

      missingMonths.forEach((month) => {
        const key = `${selectedYear}-${month}`;
        // Only generate if not already generating and not already generated in this session
        if (!generatingMonths.has(month) && !hasAutoGenerated.current.has(key)) {
          hasAutoGenerated.current.add(key);
          setGeneratingMonths(prev => new Set(prev).add(month));
          
          const generateSnapshot = async () => {
            try {
              const response = await fetch("/api/archive/create-snapshot", {
                method: "POST",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify({
                  year: selectedYear,
                  month: month,
                }),
              });
              if (response.ok) {
                // Refetch snapshots after creation
                setTimeout(() => {
                  refetchSnapshots();
                  setGeneratingMonths(prev => {
                    const next = new Set(prev);
                    next.delete(month);
                    return next;
                  });
                }, 1000);
              } else {
                hasAutoGenerated.current.delete(key); // Allow retry on error
                setGeneratingMonths(prev => {
                  const next = new Set(prev);
                  next.delete(month);
                  return next;
                });
              }
            } catch (error) {
              console.error("Error auto-generating snapshot:", error);
              hasAutoGenerated.current.delete(key); // Allow retry on error
              setGeneratingMonths(prev => {
                const next = new Set(prev);
                next.delete(month);
                return next;
              });
            }
          };
          // Small delay to avoid race conditions
          setTimeout(() => generateSnapshot(), 100);
        }
      });
    }
  }, [isLoading, yearSnapshots, selectedYear, currentYear, currentMonth, refetchSnapshots]);

  // Ensure 2025 is in available years
  const allYears = yearsData?.years || [currentYear];
  const availableYears = Array.from(new Set([...allYears, 2025, currentYear])).sort((a, b) => b - a);
  
  const snapshots = yearSnapshots?.snapshots || [];
  // 2025 and current year should show monthly data, older years show yearly
  const isPastYear = selectedYear < 2025;
  const isCurrentOr2025 = selectedYear >= 2025;

  // Create a map of month -> snapshot for easy lookup
  const snapshotMap = new Map<number, FinancialSnapshot>();
  let yearlySnapshot: FinancialSnapshot | null = null;

  snapshots.forEach((snapshot) => {
    if (snapshot.month !== undefined) {
      snapshotMap.set(snapshot.month, snapshot);
    } else {
      yearlySnapshot = snapshot;
    }
  });

  // For 2025, only show December. For current year, show months up to current month
  const monthsToShow = selectedYear === 2025
    ? [12] // Only December for 2025
    : selectedYear === currentYear
    ? Array.from({ length: currentMonth }, (_, i) => i + 1) // Current year shows months up to current
    : []; // Past years show yearly snapshot only

  if (isLoading) {
    return (
      <div className="p-6">
        <div>
          <h1 className="text-3xl font-bold">Financial Archive</h1>
          <p className="text-gray-600 mt-1">View historical financial data</p>
        </div>
        <div className="mt-8">
          <Loader text="Loading archive data..." size="lg" />
        </div>
      </div>
    );
  }

  return (
    <div className="p-6 max-w-7xl mx-auto">
      {/* Header */}
      <div className="mb-6">
        <h1 className="text-3xl font-bold">Financial Archive</h1>
        <p className="text-gray-600 mt-1">Historical financial snapshots</p>
      </div>

      {/* Year Selector */}
      <div className="bg-white rounded-lg shadow-sm border border-gray-200 p-4 mb-6">
        <div className="flex items-center gap-4">
          <div className="flex items-center gap-2">
            <Calendar className="w-5 h-5 text-gray-500" />
            <label className="text-sm font-medium text-gray-700">Year:</label>
            <select
              value={selectedYear}
              onChange={(e) => {
                setSelectedYear(parseInt(e.target.value));
              }}
              className="px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-purple-500"
            >
              {availableYears.map((year) => (
                <option key={year} value={year}>
                  {year}
                </option>
              ))}
            </select>
          </div>

          {selectedYear === currentYear && snapshots.length === 0 && (
            <button
              onClick={async () => {
                try {
                  const response = await fetch("/api/archive/create-snapshot", {
                    method: "POST",
                    headers: { "Content-Type": "application/json" },
                    body: JSON.stringify({
                      year: selectedYear,
                      month: currentMonth,
                    }),
                  });
                  if (response.ok) {
                    window.location.reload();
                  }
                } catch (error) {
                  console.error("Error creating snapshot:", error);
                }
              }}
              className="ml-auto px-4 py-2 bg-purple-600 text-white rounded-lg hover:bg-purple-700 transition-colors text-sm font-medium"
            >
              Create Snapshot
            </button>
          )}
        </div>
      </div>

      {/* Yearly Snapshot for Past Years */}
      {isPastYear && yearlySnapshot ? (
        <div className="space-y-6">
          <div className="text-center py-2">
            <h2 className="text-xl font-semibold text-gray-800">
              {selectedYear} Summary
            </h2>
          </div>
          <YearlySnapshotGrid snapshot={yearlySnapshot} />
        </div>
      ) : isPastYear && !yearlySnapshot ? (
        <div className="bg-yellow-50 border border-yellow-200 rounded-lg p-6 text-center">
          <p className="text-yellow-800">
            No snapshot found for {selectedYear}. Create a snapshot to view historical data.
          </p>
        </div>
      ) : (
        /* Monthly Grid for Current Year */
        <div className="space-y-6">
          {/* Year Analytics Header */}
          <div className="bg-gradient-to-r from-purple-600 to-blue-600 rounded-lg p-6 text-white">
            <div className="flex items-center justify-between mb-4">
              <div>
                <h2 className="text-2xl font-bold">{selectedYear} Financial Analytics</h2>
                <p className="text-purple-100 mt-1">
                  {snapshots.filter((s) => s.month !== undefined).length} of {selectedYear === 2025 ? 1 : 12} months recorded
                </p>
              </div>
              <div className="flex items-center gap-4">
                {snapshots.length > 0 && (
                  <>
                    <div className="text-right">
                      <p className="text-xs text-purple-200">Avg Net Worth</p>
                      <p className="text-xl font-bold">
                        {formatIndianNumber(
                          snapshots
                            .filter((s) => s.month !== undefined)
                            .reduce((sum, s) => sum + (s.netWorth || 0), 0) / 
                            Math.max(1, snapshots.filter((s) => s.month !== undefined).length)
                        )}
                      </p>
                      {selectedYear === currentYear && year2025Snapshot?.snapshot && (
                        <div className="flex items-center gap-1 mt-1">
                          {(() => {
                            const avgNetWorth = snapshots
                              .filter((s) => s.month !== undefined)
                              .reduce((sum, s) => sum + (s.netWorth || 0), 0) / 
                              Math.max(1, snapshots.filter((s) => s.month !== undefined).length);
                            const year2025NetWorth = year2025Snapshot.snapshot.netWorth || 0;
                            const increment = avgNetWorth - year2025NetWorth;
                            const incrementPercent = year2025NetWorth > 0 
                              ? ((increment / year2025NetWorth) * 100).toFixed(2)
                              : "0.00";
                            const isPositive = increment >= 0;
                            return (
                              <>
                                {isPositive ? (
                                  <TrendingUp className="w-3 h-3 text-green-300" />
                                ) : (
                                  <TrendingDown className="w-3 h-3 text-red-300" />
                                )}
                                <span className={`text-xs font-medium ${isPositive ? "text-green-300" : "text-red-300"}`}>
                                  {isPositive ? "+" : ""}{formatIndianNumber(increment)} ({isPositive ? "+" : ""}{incrementPercent}%)
                                </span>
                              </>
                            );
                          })()}
                        </div>
                      )}
                    </div>
                    <div className="w-px h-12 bg-white/20"></div>
                    <div className="text-right">
                      <p className="text-xs text-purple-200">Avg Investments</p>
                      <p className="text-xl font-bold">
                        {formatIndianNumber(
                          snapshots
                            .filter((s) => s.month !== undefined)
                            .reduce((sum, s) => sum + (s.totalInvestments || 0), 0) / 
                            Math.max(1, snapshots.filter((s) => s.month !== undefined).length)
                        )}
                      </p>
                      {selectedYear === currentYear && year2025Snapshot?.snapshot && (
                        <div className="flex items-center gap-1 mt-1">
                          {(() => {
                            const avgInvestments = snapshots
                              .filter((s) => s.month !== undefined)
                              .reduce((sum, s) => sum + (s.totalInvestments || 0), 0) / 
                              Math.max(1, snapshots.filter((s) => s.month !== undefined).length);
                            const year2025Investments = year2025Snapshot.snapshot.totalInvestments || 0;
                            const increment = avgInvestments - year2025Investments;
                            const incrementPercent = year2025Investments > 0 
                              ? ((increment / year2025Investments) * 100).toFixed(2)
                              : "0.00";
                            const isPositive = increment >= 0;
                            return (
                              <>
                                {isPositive ? (
                                  <TrendingUp className="w-3 h-3 text-green-300" />
                                ) : (
                                  <TrendingDown className="w-3 h-3 text-red-300" />
                                )}
                                <span className={`text-xs font-medium ${isPositive ? "text-green-300" : "text-red-300"}`}>
                                  {isPositive ? "+" : ""}{formatIndianNumber(increment)} ({isPositive ? "+" : ""}{incrementPercent}%)
                                </span>
                              </>
                            );
                          })()}
                        </div>
                      )}
                    </div>
                  </>
                )}
              </div>
            </div>
          </div>

          {monthsToShow.length === 0 ? (
            <div className="bg-yellow-50 border border-yellow-200 rounded-lg p-6 text-center">
              <p className="text-yellow-800">
                No monthly snapshots available for {selectedYear}.
              </p>
            </div>
          ) : (
            <div className="bg-white rounded-lg border border-gray-200 overflow-hidden">
              {/* Table Header */}
              <div className="grid grid-cols-11 gap-3 p-3 bg-gradient-to-r from-gray-50 to-gray-100 border-b-2 border-purple-200 font-semibold text-xs text-gray-700">
                <div className="flex items-center gap-1">
                  <Calendar className="w-3 h-3" />
                  <span>Month</span>
                </div>
                <div className="flex items-center gap-1">
                  <Wallet className="w-3 h-3 text-purple-600" />
                  <span>Net Worth</span>
                </div>
                <div className="flex items-center gap-1">
                  <TrendingUp className="w-3 h-3 text-blue-600" />
                  <span>Investments</span>
                </div>
                <div className="flex items-center gap-1">
                  <ArrowUpRight className="w-3 h-3 text-green-600" />
                  <span>Liquid Assets</span>
                </div>
                <div className="flex items-center gap-1">
                  <Home className="w-3 h-3 text-orange-600" />
                  <span>Fixed Assets</span>
                </div>
                <div className="flex items-center gap-1">
                  <CreditCard className="w-3 h-3 text-red-600" />
                  <span>Total Loans</span>
                </div>
                <div className="flex items-center gap-1">
                  <Home className="w-3 h-3 text-indigo-600" />
                  <span>Properties</span>
                </div>
                <div className="flex items-center gap-1">
                  <TrendingUp className="w-3 h-3 text-cyan-600" />
                  <span>Stocks + MF</span>
                </div>
                <div className="flex items-center gap-1">
                  <Wallet className="w-3 h-3 text-yellow-600" />
                  <span>Provident Fund</span>
                </div>
                <div className="flex items-center gap-1">
                  <ArrowUpRight className="w-3 h-3 text-emerald-600" />
                  <span>Receivables</span>
                </div>
                <div className="flex items-center gap-1">
                  <RefreshCw className="w-3 h-3 text-gray-600" />
                  <span>Last Updated</span>
                </div>
              </div>
              
              {/* Table Rows */}
              <div className="divide-y divide-gray-200">
                {monthsToShow.map((month) => {
                  const snapshot = snapshotMap.get(month);
                  // Get previous month snapshot for growth calculation
                  let previousSnapshot: FinancialSnapshot | null = null;
                  if (month > 1) {
                    previousSnapshot = snapshotMap.get(month - 1) || null;
                  } else if (month === 1 && selectedYear > 2025) {
                    // For January, check December of previous year
                    previousSnapshot = null; // Would need to fetch from previous year
                  }
                  
                  return (
                    <MonthRow
                      key={month}
                      month={month}
                      monthName={FULL_MONTHS[month - 1]}
                      snapshot={snapshot}
                      previousSnapshot={previousSnapshot}
                      isCurrentMonth={month === currentMonth && selectedYear === currentYear}
                      isGenerating={generatingMonths.has(month)}
                      isUpdating={updatingMonths.has(month)}
                      selectedYear={selectedYear}
                      onUpdate={async () => {
                        setUpdatingMonths(prev => new Set(prev).add(month));
                        try {
                          const response = await fetch("/api/archive/create-snapshot", {
                            method: "POST",
                            headers: { "Content-Type": "application/json" },
                            body: JSON.stringify({
                              year: selectedYear,
                              month: month,
                            }),
                          });
                          if (response.ok) {
                            await refetchSnapshots();
                            setUpdatingMonths(prev => {
                              const next = new Set(prev);
                              next.delete(month);
                              return next;
                            });
                          } else {
                            const error = await response.json();
                            alert(error.error || "Failed to update snapshot");
                            setUpdatingMonths(prev => {
                              const next = new Set(prev);
                              next.delete(month);
                              return next;
                            });
                          }
                        } catch (error) {
                          console.error("Error updating snapshot:", error);
                          alert("Error updating snapshot. Please try again.");
                          setUpdatingMonths(prev => {
                            const next = new Set(prev);
                            next.delete(month);
                            return next;
                          });
                        }
                      }}
                    />
                  );
                })}
                
                {/* Add button for upcoming months if current year */}
                {selectedYear === currentYear && currentMonth < 12 && (
                  <div className="p-3 text-center border-t border-gray-200">
                    <button
                      onClick={async () => {
                        try {
                          const response = await fetch("/api/archive/create-snapshot", {
                            method: "POST",
                            headers: { "Content-Type": "application/json" },
                            body: JSON.stringify({
                              year: selectedYear,
                              month: currentMonth + 1,
                            }),
                          });
                          if (response.ok) {
                            window.location.reload();
                          }
                        } catch (error) {
                          console.error("Error creating snapshot:", error);
                        }
                      }}
                      className="px-4 py-2 bg-purple-600 text-white rounded-lg hover:bg-purple-700 transition-colors text-sm font-medium"
                    >
                      Generate Report for {FULL_MONTHS[currentMonth]}
                    </button>
                  </div>
                )}
                
              </div>
            </div>
          )}
        </div>
      )}
    </div>
  );
}

function MonthRow({
  month,
  monthName,
  snapshot,
  previousSnapshot,
  isCurrentMonth,
  isGenerating = false,
  isUpdating = false,
  selectedYear,
  onUpdate,
}: {
  month: number;
  monthName: string;
  snapshot?: FinancialSnapshot;
  previousSnapshot?: FinancialSnapshot | null;
  isCurrentMonth: boolean;
  isGenerating?: boolean;
  isUpdating?: boolean;
  selectedYear: number;
  onUpdate?: () => void;
}) {
  const hasData = !!snapshot;
  
  // Calculate difference from previous month
  const calculateDifference = (current: number, previous: number): number => {
    return current - previous;
  };
  
  const formatDifference = (diff: number) => {
    const isPositive = diff >= 0;
    return {
      value: Math.abs(diff),
      isPositive,
      sign: isPositive ? "+" : "-",
    };
  };
  
  const netWorthDiff = snapshot && previousSnapshot
    ? formatDifference(calculateDifference(snapshot.netWorth, previousSnapshot.netWorth))
    : null;
    
  const investmentsDiff = snapshot && previousSnapshot
    ? formatDifference(calculateDifference(snapshot.totalInvestments, previousSnapshot.totalInvestments))
    : null;
    
  const liquidAssetsDiff = snapshot && previousSnapshot
    ? formatDifference(calculateDifference(snapshot.totalLiquidAssets, previousSnapshot.totalLiquidAssets))
    : null;
    
  const fixedAssetsDiff = snapshot && previousSnapshot
    ? formatDifference(calculateDifference(snapshot.totalFixedAssets, previousSnapshot.totalFixedAssets))
    : null;

  // Calculate combined stocks + mutual funds
  const stocksAndMF = snapshot 
    ? (snapshot.totalStocks || 0) + (snapshot.totalMutualFunds || 0)
    : 0;
    
  const stocksAndMFDiff = snapshot && previousSnapshot
    ? formatDifference(calculateDifference(
        (snapshot.totalStocks || 0) + (snapshot.totalMutualFunds || 0),
        (previousSnapshot.totalStocks || 0) + (previousSnapshot.totalMutualFunds || 0)
      ))
    : null;
    
  const loansDiff = snapshot && previousSnapshot
    ? formatDifference(calculateDifference(snapshot.totalLoans, previousSnapshot.totalLoans))
    : null;
    
  const propertiesDiff = snapshot && previousSnapshot
    ? formatDifference(calculateDifference(snapshot.totalProperties, previousSnapshot.totalProperties))
    : null;
    
  const ppfDiff = snapshot && previousSnapshot
    ? formatDifference(calculateDifference(snapshot.totalPPF || 0, previousSnapshot.totalPPF || 0))
    : null;
    
  const receivablesDiff = snapshot && previousSnapshot
    ? formatDifference(calculateDifference(snapshot.totalReceivables || 0, previousSnapshot.totalReceivables || 0))
    : null;

  return (
    <div className={`grid grid-cols-11 gap-3 p-3 hover:bg-gray-50 transition-colors border-l-4 ${
      hasData 
        ? isCurrentMonth 
          ? "bg-purple-50 border-purple-500" 
          : "bg-white border-green-500"
        : "bg-gray-50 border-gray-300"
    }`}>
        {/* Month Column */}
        <div className="flex items-center min-w-0">
          <div className="flex items-center gap-2 min-w-0">
            {hasData ? (
              <CheckCircle2 className="w-4 h-4 text-green-600 flex-shrink-0" />
            ) : (
              <XCircle className="w-4 h-4 text-gray-400 flex-shrink-0" />
            )}
            <div className="min-w-0">
              <p className="text-xs font-medium text-gray-500">{MONTHS[month - 1]}</p>
              <p className="text-sm font-semibold text-gray-900 truncate">{monthName}</p>
              {isCurrentMonth && (
                <span className="inline-block mt-0.5 px-1.5 py-0.5 bg-purple-100 text-purple-700 text-xs font-medium rounded">
                  Current
                </span>
              )}
            </div>
          </div>
        </div>

      {/* Net Worth Column */}
      <div className="flex items-center">
        {hasData ? (
          <div>
            <p className="text-sm font-semibold text-purple-700">
              {formatIndianNumber(snapshot.netWorth)}
            </p>
            {netWorthDiff && (
              <div className="flex items-center gap-0.5 mt-0.5">
                {netWorthDiff.isPositive ? (
                  <TrendingUp className="w-2.5 h-2.5 text-green-600" />
                ) : (
                  <TrendingDown className="w-2.5 h-2.5 text-red-600" />
                )}
                <span
                  className={`text-xs font-medium ${
                    netWorthDiff.isPositive ? "text-green-600" : "text-red-600"
                  }`}
                >
                  {netWorthDiff.sign}
                  {formatIndianNumber(netWorthDiff.value)}
                </span>
              </div>
            )}
          </div>
        ) : (
          <div className="flex items-center gap-2">
            {isGenerating ? (
              <div className="flex items-center gap-1 text-xs text-purple-600">
                <Loader text="" size="sm" />
                <span>Generating...</span>
              </div>
            ) : selectedYear === new Date().getFullYear() ? (
              <button
                onClick={async () => {
                  try {
                    const response = await fetch("/api/archive/create-snapshot", {
                      method: "POST",
                      headers: { "Content-Type": "application/json" },
                      body: JSON.stringify({
                        year: selectedYear,
                        month: month,
                      }),
                    });
                    if (response.ok) {
                      window.location.reload();
                    } else {
                      const error = await response.json();
                      alert(error.error || "Failed to create snapshot");
                    }
                  } catch (error) {
                    console.error("Error creating snapshot:", error);
                    alert("Error creating snapshot. Please try again.");
                  }
                }}
                className="text-xs text-purple-600 hover:text-purple-700 font-medium px-2 py-1 bg-purple-50 rounded hover:bg-purple-100 transition-colors"
              >
                Create
              </button>
            ) : (
              <span className="text-xs text-gray-400">-</span>
            )}
          </div>
        )}
      </div>

      {/* Investments Column */}
      <div className="flex items-center">
        {hasData ? (
          <div>
            <p className="text-sm font-semibold text-blue-700">
              {formatIndianNumber(snapshot.totalInvestments)}
            </p>
            {investmentsDiff && (
              <div className="flex items-center gap-0.5 mt-0.5">
                {investmentsDiff.isPositive ? (
                  <TrendingUp className="w-2.5 h-2.5 text-green-600" />
                ) : (
                  <TrendingDown className="w-2.5 h-2.5 text-red-600" />
                )}
                <span
                  className={`text-xs font-medium ${
                    investmentsDiff.isPositive ? "text-green-600" : "text-red-600"
                  }`}
                >
                  {investmentsDiff.sign}
                  {formatIndianNumber(investmentsDiff.value)}
                </span>
              </div>
            )}
          </div>
        ) : (
          <span className="text-xs text-gray-400">-</span>
        )}
      </div>

      {/* Liquid Assets Column */}
      <div className="flex items-center">
        {hasData ? (
          <div>
            <p className="text-sm font-semibold text-green-700">
              {formatIndianNumber(snapshot.totalLiquidAssets)}
            </p>
            {liquidAssetsDiff && (
              <div className="flex items-center gap-0.5 mt-0.5">
                {liquidAssetsDiff.isPositive ? (
                  <TrendingUp className="w-2.5 h-2.5 text-green-600" />
                ) : (
                  <TrendingDown className="w-2.5 h-2.5 text-red-600" />
                )}
                <span
                  className={`text-xs font-medium ${
                    liquidAssetsDiff.isPositive ? "text-green-600" : "text-red-600"
                  }`}
                >
                  {liquidAssetsDiff.sign}
                  {formatIndianNumber(liquidAssetsDiff.value)}
                </span>
              </div>
            )}
          </div>
        ) : (
          <span className="text-xs text-gray-400">-</span>
        )}
      </div>

      {/* Fixed Assets Column */}
      <div className="flex items-center">
        {hasData ? (
          <div>
            <p className="text-sm font-semibold text-orange-700">
              {formatIndianNumber(snapshot.totalFixedAssets)}
            </p>
            {fixedAssetsDiff && (
              <div className="flex items-center gap-0.5 mt-0.5">
                {fixedAssetsDiff.isPositive ? (
                  <TrendingUp className="w-2.5 h-2.5 text-green-600" />
                ) : (
                  <TrendingDown className="w-2.5 h-2.5 text-red-600" />
                )}
                <span
                  className={`text-xs font-medium ${
                    fixedAssetsDiff.isPositive ? "text-green-600" : "text-red-600"
                  }`}
                >
                  {fixedAssetsDiff.sign}
                  {formatIndianNumber(fixedAssetsDiff.value)}
                </span>
              </div>
            )}
          </div>
        ) : (
          <span className="text-xs text-gray-400">-</span>
        )}
      </div>

      {/* Total Loans Column */}
      <div className="flex items-center">
        {hasData ? (
          <div>
            <p className="text-sm font-semibold text-red-700">
              {formatIndianNumber(snapshot.totalLoans)}
            </p>
            {loansDiff && (
              <div className="flex items-center gap-0.5 mt-0.5">
                {loansDiff.isPositive ? (
                  <TrendingUp className="w-2.5 h-2.5 text-green-600" />
                ) : (
                  <TrendingDown className="w-2.5 h-2.5 text-red-600" />
                )}
                <span
                  className={`text-xs font-medium ${
                    loansDiff.isPositive ? "text-green-600" : "text-red-600"
                  }`}
                >
                  {loansDiff.sign}
                  {formatIndianNumber(loansDiff.value)}
                </span>
              </div>
            )}
          </div>
        ) : (
          <span className="text-xs text-gray-400">-</span>
        )}
      </div>

      {/* Total Properties Column */}
      <div className="flex items-center">
        {hasData ? (
          <div>
            <p className="text-sm font-semibold text-indigo-700">
              {formatIndianNumber(snapshot.totalProperties)}
            </p>
            {propertiesDiff && (
              <div className="flex items-center gap-0.5 mt-0.5">
                {propertiesDiff.isPositive ? (
                  <TrendingUp className="w-2.5 h-2.5 text-green-600" />
                ) : (
                  <TrendingDown className="w-2.5 h-2.5 text-red-600" />
                )}
                <span
                  className={`text-xs font-medium ${
                    propertiesDiff.isPositive ? "text-green-600" : "text-red-600"
                  }`}
                >
                  {propertiesDiff.sign}
                  {formatIndianNumber(propertiesDiff.value)}
                </span>
              </div>
            )}
          </div>
        ) : (
          <span className="text-xs text-gray-400">-</span>
        )}
      </div>

      {/* Stocks + Mutual Fund Column */}
      <div className="flex items-center">
        {hasData ? (
          <div>
            <p className="text-sm font-semibold text-cyan-700">
              {formatIndianNumber(stocksAndMF)}
            </p>
            {stocksAndMFDiff && (
              <div className="flex items-center gap-0.5 mt-0.5">
                {stocksAndMFDiff.isPositive ? (
                  <TrendingUp className="w-2.5 h-2.5 text-green-600" />
                ) : (
                  <TrendingDown className="w-2.5 h-2.5 text-red-600" />
                )}
                <span
                  className={`text-xs font-medium ${
                    stocksAndMFDiff.isPositive ? "text-green-600" : "text-red-600"
                  }`}
                >
                  {stocksAndMFDiff.sign}
                  {formatIndianNumber(stocksAndMFDiff.value)}
                </span>
              </div>
            )}
          </div>
        ) : (
          <span className="text-xs text-gray-400">-</span>
        )}
      </div>

      {/* Provident Fund Column */}
      <div className="flex items-center">
        {hasData ? (
          <div>
            <p className="text-sm font-semibold text-yellow-700">
              {formatIndianNumber(snapshot.totalPPF || 0)}
            </p>
            {ppfDiff && (
              <div className="flex items-center gap-0.5 mt-0.5">
                {ppfDiff.isPositive ? (
                  <TrendingUp className="w-2.5 h-2.5 text-green-600" />
                ) : (
                  <TrendingDown className="w-2.5 h-2.5 text-red-600" />
                )}
                <span
                  className={`text-xs font-medium ${
                    ppfDiff.isPositive ? "text-green-600" : "text-red-600"
                  }`}
                >
                  {ppfDiff.sign}
                  {formatIndianNumber(ppfDiff.value)}
                </span>
              </div>
            )}
          </div>
        ) : (
          <span className="text-xs text-gray-400">-</span>
        )}
      </div>

      {/* Receivables Column */}
      <div className="flex items-center">
        {hasData ? (
          <div>
            <p className="text-sm font-semibold text-emerald-700">
              {formatIndianNumber(snapshot.totalReceivables || 0)}
            </p>
            {receivablesDiff && (
              <div className="flex items-center gap-0.5 mt-0.5">
                {receivablesDiff.isPositive ? (
                  <TrendingUp className="w-2.5 h-2.5 text-green-600" />
                ) : (
                  <TrendingDown className="w-2.5 h-2.5 text-red-600" />
                )}
                <span
                  className={`text-xs font-medium ${
                    receivablesDiff.isPositive ? "text-green-600" : "text-red-600"
                  }`}
                >
                  {receivablesDiff.sign}
                  {formatIndianNumber(receivablesDiff.value)}
                </span>
              </div>
            )}
          </div>
        ) : (
          <span className="text-xs text-gray-400">-</span>
        )}
      </div>

      {/* Last Updated Column */}
      <div className="flex items-center">
        {hasData && snapshot ? (
          <div className="flex flex-col gap-1.5">
            <div className="text-xs text-gray-600">
              <p className="font-medium">
                {new Date(snapshot.updatedAt).toLocaleDateString('en-US', {
                  month: 'short',
                  day: 'numeric',
                  year: 'numeric'
                })}
              </p>
              <p className="text-gray-500 mt-0.5">
                {new Date(snapshot.updatedAt).toLocaleTimeString('en-US', {
                  hour: '2-digit',
                  minute: '2-digit',
                  hour12: true
                })}
              </p>
            </div>
            {isCurrentMonth && onUpdate && (
              <button
                onClick={onUpdate}
                disabled={isUpdating}
                className="px-2 py-1 text-xs font-medium text-purple-600 hover:text-purple-700 bg-purple-50 hover:bg-purple-100 rounded transition-colors disabled:opacity-50 disabled:cursor-not-allowed flex items-center gap-1 w-fit"
                title="Update current month data"
              >
                {isUpdating ? (
                  <>
                    <Loader text="" size="sm" />
                    <span>Updating...</span>
                  </>
                ) : (
                  <>
                    <RefreshCw className="w-3 h-3" />
                    <span>Update</span>
                  </>
                )}
              </button>
            )}
          </div>
        ) : (
          <span className="text-xs text-gray-400">-</span>
        )}
      </div>
    </div>
  );
}

function MetricRow({
  label,
  value,
  icon,
  highlight = false,
}: {
  label: string;
  value: number;
  icon: React.ReactNode;
  highlight?: boolean;
}) {
  return (
    <div className="flex items-center justify-between">
      <div className="flex items-center gap-2">
        <div className="text-gray-400">{icon}</div>
        <span className={`text-xs ${highlight ? "font-semibold" : ""} text-gray-600`}>
          {label}
        </span>
      </div>
      <span className={`${highlight ? "text-lg font-bold" : "text-sm font-semibold"} text-gray-900`}>
        {formatIndianNumber(value)}
      </span>
    </div>
  );
}

function YearlySnapshotGrid({ snapshot }: { snapshot: FinancialSnapshot }) {
  return (
    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
      <GridCard
        label="Net Worth"
        value={snapshot.netWorth}
        icon={<Wallet className="w-5 h-5" />}
        highlight
      />
      <GridCard
        label="Investments"
        value={snapshot.totalInvestments}
        icon={<TrendingUp className="w-5 h-5" />}
      />
      <GridCard
        label="Income"
        value={snapshot.totalIncome}
        icon={<ArrowUpRight className="w-5 h-5" />}
      />
      <GridCard
        label="Expenses"
        value={snapshot.totalExpenses}
        icon={<ArrowDownRight className="w-5 h-5" />}
      />
      <GridCard
        label="Properties"
        value={snapshot.totalProperties}
        icon={<TrendingUp className="w-5 h-5" />}
      />
      <GridCard
        label="Loans"
        value={snapshot.totalLoans}
        icon={<ArrowDownRight className="w-5 h-5" />}
      />
      <GridCard
        label="Bank Balance"
        value={snapshot.totalBankBalances}
        icon={<Wallet className="w-5 h-5" />}
      />
      <GridCard
        label="Net Balance"
        value={snapshot.netBalance}
        icon={<Wallet className="w-5 h-5" />}
      />
      <GridCard
        label="Fixed Assets"
        value={snapshot.totalFixedAssets}
        icon={<TrendingUp className="w-5 h-5" />}
      />
    </div>
  );
}

function GridCard({
  label,
  value,
  icon,
  highlight = false,
}: {
  label: string;
  value: number;
  icon: React.ReactNode;
  highlight?: boolean;
}) {
  return (
    <div
      className={`bg-white rounded-lg border border-gray-200 p-5 hover:shadow-md transition-shadow ${
        highlight ? "border-purple-300 bg-purple-50/30" : ""
      }`}
    >
      <div className="flex items-center justify-between mb-3">
        <p className={`text-sm font-medium ${highlight ? "text-purple-700" : "text-gray-600"}`}>
          {label}
        </p>
        <div className={`${highlight ? "text-purple-600" : "text-gray-400"}`}>{icon}</div>
      </div>
      <p className={`${highlight ? "text-3xl" : "text-2xl"} font-bold text-gray-900`}>
        {formatIndianNumber(value)}
      </p>
    </div>
  );
}
